export const FACEBOOK_SHARE_STATUS = {
  READY            : 'FACEBOOK/SHARE_READY',
  LOADING          : 'FACEBOOK/SHARE_LOADING',
  SUCCESS          : 'FACEBOOK/SHARE_SUCCESS',
  FAILURE          : 'FACEBOOK/SHARE_FAILURE',
  PERMISSION_DENIED: 'FACEBOOK/SHARE_PERMISSION_DENIED',
}