export const QUIZ_STATE = {
  LOADING: 'QUIZ_LOADING',
  LOGIN  : 'QUIZ_LOGIN',
  INIT   : 'QUIZ_INIT',
  PLAY   : 'QUIZ_PLAY',
  END    : 'QUIZ_END',
}

export const QUIZ_TYPE = {
  SUPERTEST: 'QUIZ_TYPE_SUPERTEST',
  MAZE     : 'QUIZ_TYPE_MAZE',
  FUNNY    : 'QUIZ_TYPE_FUNNY',
  SOCIAL   : 'QUIZ_TYPE_SOCIAL',
}